### ISSUE TITLE
Occasional warnings for LaunchKit under Carthage

### ISSUE THREAD

**Issue by ksm** [LaunchKit/launchkit-ios#10]
I'm getting multiple `umbrella header for module LaunchKit does not include header` warnings when building my project. I've had these warnings disappear and then reappear occasionally. I'm on Carthage 0.11 and Xcode 7.2. I build my Carthage dependencies using `carthage update --platform iOS --no-use-binaries`.

Screenshot:
<img width="583" alt="screen shot 2016-01-19 at 14 37 01" src="https://cloud.githubusercontent.com/assets/747910/12437087/2827615e-bf5e-11e5-9b77-f12acc73de7c.png">

Anyone seen this? I haven't seen a similar problem in other Carthage-installed dependencies.

**Comment by rsattar** [comment]
Hey @ksm thanks for filing the issue. I've seen others have that issue with some other Carthage projects.  I'll take a look to see if there's anything I can do. In the meantime, if you clean your project and build folder, do the warnings go away (and then come back later)?

**Comment by rsattar** [comment]
@ksm Would you mind trying out version `1.2.0` from Carthage. I was able to reproduce the problem, and changing the imports to be library imports appeared to fix the issue in my test project. However, I saw the warnings re-appear once, but I can't reproduce it again :(

**Comment by ksm** [comment]
Did a "Clean Build Folder..." and then quit Xcode. Upgraded to `1.2.0` and rebuilt with Carthage. Built app and ran in simulator – the warnings reappeared. Then did a "Clean" action and built and ran app on simulator again. Warnings went away.

So yeah.. this is a fishy bug. Gone for now at least. Thank you so much for the help.

**Comment by rsattar** [comment]
Argh! Ok, thanks for testing it! Will keep working at it!

**Comment by ksm** [comment]
Closing the issue, since the problem is gone for now for me.

**Comment by ksm** [comment]
Update: when I built for a real device the warnings reappeared. I did a clean and rebuilt and they went away.
