### ISSUE TITLE
Can't force presentation of release notes

### ISSUE THREAD

**Issue by bryanbartow** [LaunchKit/launchkit-ios#13]
Although it was working in a previous release, I just tried calling the `forcePresentationOfAppReleaseNotesFromViewController` method and it had no effect. Not sure if this is a Swift 2.2 and/or Xcode 7.3 bug.

**Comment by rsattar** [comment]
@bryanbartow Thanks for the find! This should be fixed in `2.1.2`. Thanks!

**Comment by bryanbartow** [comment]
@rsattar No worries. I was just about to hit you up on Slack. No reason to, I guess. Thanks for fixing.
