### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by olutsenko** [LaunchKit/launchkit-ios#4]
Hello,

Library uses some APIs that are not available on tvOS.

Could you please improve the library by supporting tvOS as well?

Regards,
Oleg

<img width="860" alt="screenshot 2015-11-03 12 57 35" src="https://cloud.githubusercontent.com/assets/303121/10907467/9abbf7f0-822a-11e5-94e3-5d70b5af5b61.png">

**Comment by rsattar** [comment]
Thanks @olutsenko, it's on my list and shouldn't be too bad to to add support for it.
