### ISSUE TITLE
Release Notes On First launch After Install

### ISSUE THREAD

**Issue by acegreen** [LaunchKit/launchkit-ios#7]
I'm noticing that the release notes card doesn't show up after first launch after a fresh install. It does present when I force close the app and relaunch it.

Is that the expected behaviour?

**Comment by rsattar** [comment]
Hey @acegreen, try updating to `2.1.1`. I pushed some fixes to make sure release notes are displaying correctly. There was a small bug where LaunchKit couldn't tell if you were a "new-to-the-app" user or a "new-to-LaunchKit" user :)
